"""initial schema

Revision ID: 7eacf30adcdb
Revises: 
Create Date: 2026-09-24 00:01:19.073778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eacf30adcdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_name'), ['name'], unique=True)

    op.create_table('ldap_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=256), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('base_dn', sa.String(length=512), nullable=True),
    sa.Column('bind_dn', sa.String(length=512), nullable=True),
    sa.Column('bind_password', sa.String(length=512), nullable=True),
    sa.Column('user_filter', sa.Text(), nullable=True),
    sa.Column('username_attr', sa.String(length=64), nullable=True),
    sa.Column('email_attr', sa.String(length=64), nullable=True),
    sa.Column('display_name_attr', sa.String(length=64), nullable=True),
    sa.Column('tls_verify', sa.Boolean(), nullable=True),
    sa.Column('use_ssl', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ldap_group_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_dn', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('apps', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_dn')
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('hashed_password', sa.String(length=256), nullable=True),
    sa.Column('auth_type', sa.String(length=16), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('allowed_apps', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('image_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=256), nullable=False),
    sa.Column('digest', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_tags', schema=None) as batch_op:
        batch_op.create_index('ix_image_tags_app_tag', ['application_id', 'tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_tags_application_id'), ['application_id'], unique=False)

    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_tag_id', sa.String(length=36), nullable=False),
    sa.Column('scanner', sa.String(length=64), nullable=False),
    sa.Column('scan_type', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_tag_id'], ['image_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_image_tag_id'), ['image_tag_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('scanner', sa.String(length=64), nullable=False),
    sa.Column('scan_type', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('cwe', sa.String(length=32), nullable=True),
    sa.Column('cve', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('found_at', sa.DateTime(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_dedup_hash'), ['dedup_hash'], unique=False)
        batch_op.create_index('ix_findings_scan_dedup', ['scan_id', 'dedup_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_scan_id'))
        batch_op.drop_index('ix_findings_scan_dedup')
        batch_op.drop_index(batch_op.f('ix_findings_dedup_hash'))

    op.drop_table('findings')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_image_tag_id'))

    op.drop_table('scans')
    with op.batch_alter_table('image_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_tags_application_id'))
        batch_op.drop_index('ix_image_tags_app_tag')

    op.drop_table('image_tags')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('system_config')
    op.drop_table('ldap_group_mappings')
    op.drop_table('ldap_config')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_name'))

    op.drop_table('applications')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
